version: 2

defaults: &defaults
  docker:
  - image: groupbyinc/circleci-java

main_branch_only: &main_branch_only
  filters:
    branches:
      only:
        - develop

cache_key: &cache_key
  key: v1-dependencies-parent-pom

restore_cache: &restore_cache
  restore_cache: *cache_key

setup_builder: &setup_builder
  run:
    name: Initialize Build Agent
    command: /scripts/setup.sh

jobs:
  release:
    <<: *defaults
    steps:
    - checkout
    - *restore_cache
    - *setup_builder
    - run: mvn -B release:prepare release:perform
    - run: mvn -B dependency:go-offline
    - save_cache:
        <<: *cache_key
        paths:
        - ~/.m2

workflows:
  version: 2
  release:
    jobs:
    - hold:
        <<: *main_branch_only
        type: approval
    - release:
        <<: *main_branch_only
        context: org-global
        requires:
        - hold
