version: 2

defaults: &defaults
  docker:
  - image: groupbyinc/circleci-java

main_branch_only: &main_branch_only
  filters:
    branches:
      only:
        - develop

cache_key: &cache_key
  key: v1-dependencies-parent-pom

setup_builder: &setup_builder
  run:
    name: Initialize Build Agent
    command: /scripts/setup.sh

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *cache_key
    - *setup_builder
    - run: mvn -B clean install
    - run: mvn -B dependency:go-offline
    - save_cache:
        <<: *cache_key
        paths:
        - ~/.m2
  release:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *cache_key
    - *setup_builder
    - run: mvn -B release:prepare
    - run: mvn - B deploy

workflows:
  version: 2
  build-and-push:
    jobs:
    - build:
        context: org-global
    - hold:
        <<: *main_branch_only
        type: approval
        requires:
        - build
    - release:
        <<: *main_branch_only
        context: org-global
        requires:
        - hold
